BaseURL = "https://mithy.fun/"
LanguageCode = "ja-JP"
HasCJKLanguage = true
title = "Mity"
theme = "primer"
summaryLength = 70
# Code pen
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-133713641-1"
publishDir = "docs"
enableGitInfo = true
copyright = "&copy;Mamoru Machida 2019"

[Author]
  Name = "Mamoru Machida"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[params]
  Subtitle = ""
  Twitter = "mcho71"
  GitHub = "Mamoru Machida"
  DateFormat = "2006-01-02"
  MonthFormat = "2006-01"
  shareTo = ["Twitter", "Hatena", "Facebook"]
  creditHugoPrimer = true
  useIcon = true
  UseTwitterCard = true

[related]
  threthold = 80
  includeNewer = true
  toLower = false
[[related.indices]]
  name = "tags"
  weight = 80
[[related.indices]]
  name = "categories"
  weight = 80
