BaseURL = "https://mithy.fun/"
LanguageCode = "ja-JP"
HasCJKLanguage = true
title = "Mity"
theme = "primer"
summaryLength = 70
# Code pen
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-133713641-1"
publishDir = "docs"
enableGitInfo = true
copyright = "&copy;machos 2019"

[Author]
  Name = "MamoruMachida"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[params]
  Subtitle = ""
  Twitter = "machos71"
  GitHub = "MamoruMachida"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  shareTo = ["Twitter", "Hatena", "Facebook"]
  creditHugoPrimer = true
  useIcon = true
  UseTwitterCard = true

[related]
  threthold = 80
  includeNewer = true
  toLower = false
[[related.indices]]
  name = "tags"
  weight = 80
[[related.indices]]
  name = "categories"
  weight = 50
[[related.indices]]
  name = "date"
  weight = 50
